### ISSUE TITLE
Installation: cannot type switch on non-interface value tweet.Coordinates

### ISSUE THREAD

**Issue by cjejung** [SocialHarvest/harvester#65]
Hi,

Just trying to follow the installation instruction on https://github.com/SocialHarvest/harvester.

I typed the following:
go get github.com/SocialHarvest/harvester

All I get ist the error:^
Go\src\github.com\SocialHarvest\harvester\lib\harvester\twitter.go:95: cannot type switch on non-interface value tweet.Coordinates (type *anaconda.Coordinates)

What am I doing wrong?

**Comment by tmaiaroto** [comment]
Likely nothing. I may need to vendor that anaconda package. The dependency may have changed. I'll take a deeper look soon.

**Comment by tmaiaroto** [comment]
This should now be resolved (sorry about not having test cases yet).

**Comment by cjejung** [comment]
Thanks a lot!

Chris

On 24 February 2015 at 14:24, Tom Maiaroto <notifications@github.com> wrote:

> This should now be resolved (sorry about not having test cases yet).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SocialHarvest/harvester/issues/65#issuecomment-75755123>
> .
>



-- 
---
Christopher Jung
a: Schönleinstr. 6; 10967 Berlin; Germany
t: +49 (0) 170 4529 767
