### ISSUE TITLE
Problems with go1.4.2 vs go1.3

### ISSUE THREAD

**Issue by cjejung** [SocialHarvest/harvester#66]
I tried to "go get github.com/SocialHarvest/harvester" and got the following error message:

Go\src\github.com\SocialHarvest\harvester\lib\harvester\facebook.go:20: import C:\Users\cjung\Go\pkg\windows_amd64/github.com/SocialHarvest/harvester/lib/config.a: object is[windows amd64 go1.3 X:precisestack] expected [windows amd64 go1.4.2 X:precisestack]

Installed go 1.3 instead. When I try "go get github.com/SocialHarvest/hervester" I get the following error message:

Go\src\github.com\SocialHarvest\harvester\lib\harvester\twitter.go:95: cannot type switch on non-interface value tweet.Coordinates (type *anaconda.Coordinates) Go\src\github.com\SocialHarvest\harvester\lib\harvester\twitter.go:416: cannot type switch on non-interface value tweet.Coordinates (type *anaconda.Coordinates)

**Comment by tmaiaroto** [comment]
I'll look into the facebook package as well. I'm not having any issues with go 1.4 on OS X. I'll take a deeper look into this soon.

I still need to "vendor" these 3rd party packages so I can lock them down to their current versions. This is something on the to do list before Social Harvest enters "beta." I was trying to leave that until later on, but with them changing so frequently and more people trying to use Social Harvest, I'll do it sooner so things are more stable for folks.

**Comment by cjejung** [comment]
Thanks! In the meantime i'll have go on go 1.4 (using windows though).
Cheers!

Chris


On Tuesday, February 24, 2015, Tom Maiaroto <notifications@github.com>
wrote:

> I'll look into the facebook package as well. I'm not having any issues
> with go 1.4 on OS X. I'll take a deeper look into this soon.
>
> I still need to "vendor" these 3rd party packages so I can lock them down
> to their current versions. This is something on the to do list before
> Social Harvest enters "beta." I was trying to leave that until later on,
> but with them changing so frequently and more people trying to use Social
> Harvest, I'll do it sooner so things are more stable for folks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SocialHarvest/harvester/issues/66#issuecomment-75821023>
> .
>


-- 
---
Christopher Jung
a: Schönleinstr. 6; 10967 Berlin; Germany
t: +49 (0) 170 4529 767

**Comment by tmaiaroto** [comment]
Try removing the package and getting it again. Also ensure ```C:\Users\cjung\Go\pkg\windows_amd64/github.com/SocialHarvest/harvester``` is removed.

**Comment by bigdriveca** [comment]
Same issue here - I'm on go1.4.1 I removed /harvester directory and tried getting it again and got:

root@ip-172-31-31-158:/usr/local/go/src/github.com/SocialHarvest# go get -u github.com/SocialHarvest/harvester
# github.com/SocialHarvest/harvester/lib/config
/usr/local/gopath/src/github.com/SocialHarvest/harvester/lib/config/database.go:22: import /usr/local/go/pkg/linux_amd64/github.com/jmoiron/sqlx.a: object is [linux amd64 go1.2.1 X:none] expected [linux amd64 go1.4.1 X:precisestack]
# github.com/ChimeraCoder/anaconda
../ChimeraCoder/anaconda/twitter.go:50: import /usr/local/go/pkg/linux_amd64/github.com/ChimeraCoder/tokenbucket.a: object is [linux amd64 go1.2.1 X:none] expected [linux amd64 go1.4.1 X:precisestack]

Cheers,
Dave

**Comment by tmaiaroto** [comment]
I'll try from a fresh install of Go. These error messages are typically seen between different versions of Go and local cache. I have seen similar errors in the past for other projects and can't quite remember how I remedied it, but I'll find out.

**Comment by bigdriveca** [comment]
Thanks - I dropped a fresh  go1.3.3 on there and it works fine. No rush. You're correct - I had 1.2 on there then put on 1.4 with gvm so I think it was a version clash somewhere.

**Comment by tmaiaroto** [comment]
There's still some reported issues along the same lines and I think it stems from different package versions. I will vendor the packages locking things down more.

**Comment by tmaiaroto** [comment]
Sorry, it took longer than expected. Can you please re-check to see if this is still an issue for you? I've vendored pretty much all the packages Social Harvest uses so they are locked down. I will update and cherry pick as necessary, but the functionality of them satisfies Social Harvest's needs - so I wouldn't expect frequent updates. Though at least this way there's more control.

All that said, because nothing (3rd party) should change now and since it seems to work for me after running a ```go get -u all``` I think it should be ok...But let me know. Thanks!
