### ISSUE TITLE
Go get is returning an error

### ISSUE THREAD

**Issue by Benoss** [SocialHarvest/harvester#73]
Ubuntu 14.04 with go 1.4

```
~/go $ go get github.com/SocialHarvest/harvester
# github.com/SocialHarvestVendors/sqlx
src/github.com/SocialHarvestVendors/sqlx/sqlx.go:61: invalid argument m.TypeMap(t) (type *reflectx.StructMap) for len
```

Do I need a specific version of Go to get it ?

**Comment by tmaiaroto** [comment]
1.4 should do it. I'll take a look.

**Comment by tmaiaroto** [comment]
I updated the vendor package and it seems to be getting beyond this point on my Ubuntu server. However, I believe I don't have enough RAM to build so I'm running into another signal: killed error. So could you give it a shot now? `go get -u`

**Comment by Benoss** [comment]
Worked thanks !
