### ISSUE TITLE
unrecognized import path "code.google.com/p/google-api-go-client/googleapi"

### ISSUE THREAD

**Issue by adamyala** [SocialHarvest/harvester#74]
I'm trying to build this project.

- I installed Go on MacOS via brew.
- I had to create a `$GOPATH` so I ran `export GOPATH="$HOME/Code/go-workspace/"`
- I then ran `go get github.com/SocialHarvest/harvester`
I got the below error.
```
package code.google.com/p/google-api-go-client/googleapi: unrecognized import path "code.google.com/p/google-api-go-client/googleapi" (parse https://code.google.com/p/google-api-go-client/googleapi?go-get=1: no go-import meta tags)
```
I couldn't tell if the `go get` failed or not so I tried to run it anyway and got this error:
```
Adam:~/Code/go-workspace/src/github.com/SocialHarvest/harvester $ go run main.go harvest.go
../../SocialHarvestVendors/google-api-go-client/plus/v1/plus-gen.go:14:2: cannot find package "code.google.com/p/google-api-go-client/googleapi" in any of:
	/usr/local/Cellar/go/1.7.4_2/libexec/src/code.google.com/p/google-api-go-client/googleapi (from $GOROOT)
	/Users/Adam/Code/go-workspace/src/code.google.com/p/google-api-go-client/googleapi (from $GOPATH)
```
Is this something to do with brew? Is there a recommended way to install go?

**Comment by tmaiaroto** [comment]
I see, I didn't fork that repo like the other dependencies. Since I built this Go now has vendoring, but even still I like to fork the 3rd party repos just in order to have some more cherry picking abilities and such. I'll fork this and update the import path.

The fix would be to change the import statement in any source code files to reflect the new import paths they made. It's a breaking change in their package.

You can see here:
https://code.google.com/archive/p/google-api-go-client/

They also moved it to GitHub, which is where I'll want to use it from now:
https://github.com/google/google-api-go-client

That's why the import path is unrecognized. So it's a pretty simple fix. I'll look into it soon if you are still having trouble with it.

**Comment by adamyala** [comment]
I see that a bunch of imports were fixed in https://github.com/SocialHarvest/harvester/commit/e970772d90ab6dbce1e108ff47aca468c73bc57b

I'm a go newbie and still don't quite understand. I searched the repo for any reference to code.google.com and found none. Do I have to modify actual go lang source files?

**Comment by adamyala** [comment]
I got the project to build and run. I ran a `go get`. Once I had those dependancies I search and replaced them for the correct url in you code.google.com link. Thank you for the explanation. It was also nice to get my feet wet with Go for the first time.

> So it's a pretty simple fix.

Could I ask for a quick fix to this issue? Go'd dependency system is still a complete mystery to me.

**Comment by tmaiaroto** [comment]
Go has new vendoring features since I wrote all this. I'd like to take advantage of that, but my time is limited. I'll look into this as soon as I can. You're also welcome to submit a pull request that has the correct import path if you like.

**Comment by farhanlatheef** [comment]
I am a newbie to go.  is this fixed ?.

**Comment by adamyala** [comment]
I believe this project has been abandoned. Closing issue.

**Comment by tmaiaroto** [comment]
Yea, I'm reworking this project completely the next opportunity I get. Not that others aren't welcome to work on this or use bits and pieces from this. In fact, parts of this codebase will be recycled into the new project. I may even use the same repo and move the current code into a branch. So you might as well considered this abandoned.

The way this is going to be in the future is in a serverless approach. AWS Lambda now supports Golang and as soon as their Aurora DB in its serverless capacity is GA, I'll likely pick this back up again. Until those pieces fall into place, I have no interest in doing anything with this project personally. It just doesn't make much sense.

One of the goals (perhaps the main goal) of social harvest is to be able to provide affordable social media analytics/monitoring. While you could actually get away on a host like Digital Ocean for a few bucks a month and setup the database, etc. the whole configuration of Social Harvest and setting up of the servers was involved. It proved to be more technical than I'd like. 

What I'm hoping to do in the future (and I have very limited time unfortunately) is provide a turn-key solution. That was always the goal, but now with Amazon's new services coming down the road, it'll actually be possible.

So bits here will be recycled into Lambda functions as "microservices" and then data stored in Aurora. Plain and simple. I also won't focus on a front-end client anytime soon either. People can use Amazon Quicksight or open-source Metabase or any one of a dozen analytics/database querying tools out there. Mode Analytics is another one. There's plenty. So I'm not going to look to build a client right away either. I first will want to see how the new harvester bits will be used.

It'll be a good while honestly.

**Comment by nirajmchauhan** [comment]
This will be really helpful, can you share git repo link if u have already started on this?
